//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM_4_FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CURSO
    {
        public TB_CURSO()
        {
            this.TB_TURMA = new HashSet<TB_TURMA>();
        }
    
        public int COD_CURSO { get; set; }
        public string ESTAGIO_CURSO { get; set; }
        public string NOME_CURSO { get; set; }
    
        public virtual ICollection<TB_TURMA> TB_TURMA { get; set; }
    }
}
