//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM_4_FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAIXA
    {
        public TB_CAIXA()
        {
            this.TB_MENSALIDADE = new HashSet<TB_MENSALIDADE>();
        }
    
        public int COD_FUNC { get; set; }
        public Nullable<decimal> VALOR_DIA { get; set; }
        public System.DateTime DATA_CAIXA { get; set; }
    
        public virtual TB_FUNCIONARIO TB_FUNCIONARIO { get; set; }
        public virtual ICollection<TB_MENSALIDADE> TB_MENSALIDADE { get; set; }
    }
}
