//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM_4_FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_COMPRA
    {
        public TB_COMPRA()
        {
            this.TB_LIVRO = new HashSet<TB_LIVRO>();
        }
    
        public int COD_COMPRA { get; set; }
        public Nullable<int> COD_ALUNO { get; set; }
        public Nullable<decimal> VALOR_COMPRA { get; set; }
        public Nullable<System.DateTime> DATA_COMPRA { get; set; }
    
        public virtual TB_ALUNO TB_ALUNO { get; set; }
        public virtual ICollection<TB_LIVRO> TB_LIVRO { get; set; }
    }
}
