//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM_4_FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LIVRO
    {
        public TB_LIVRO()
        {
            this.TB_ALUGUEL = new HashSet<TB_ALUGUEL>();
        }
    
        public int COD_LIVRO { get; set; }
        public Nullable<decimal> PRECO_LIVRO { get; set; }
        public string NOME_LIVRO { get; set; }
        public string AUTOR_LIVRO { get; set; }
        public string EDITORA_LIVRO { get; set; }
        public string ASSUNTO_LIVRO { get; set; }
        public string IDIOMA_LIVRO { get; set; }
    
        public virtual ICollection<TB_ALUGUEL> TB_ALUGUEL { get; set; }
    }
}
