//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM_4_FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MENSALIDADE
    {
        public int COD_MENSALIDADE { get; set; }
        public int COD_ALUNO { get; set; }
        public Nullable<bool> STATUS_MENSALIDADE { get; set; }
        public Nullable<System.DateTime> DATA_MENSALIDADE { get; set; }
        public Nullable<decimal> VALOR_MENSALIDADE { get; set; }
        public Nullable<System.DateTime> DATA_CAIXA { get; set; }
    
        public virtual TB_ALUNO TB_ALUNO { get; set; }
        public virtual TB_CAIXA TB_CAIXA { get; set; }
    }
}
