//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM_4_FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROFESSOR
    {
        public TB_PROFESSOR()
        {
            this.TB_MENCAO = new HashSet<TB_MENCAO>();
            this.TB_SALA_DE_VIDEO = new HashSet<TB_SALA_DE_VIDEO>();
            this.TB_TURMA = new HashSet<TB_TURMA>();
        }
    
        public int COD_PROFESSOR { get; set; }
        public string NOME_PROFESSOR { get; set; }
        public string ORGAO_EMISSOR_PROFESSOR { get; set; }
        public Nullable<bool> WHATSAPP { get; set; }
        public System.DateTime NASC_PROFESSOR { get; set; }
        public string EMAIL_PROFESSOR { get; set; }
        public Nullable<decimal> SALARIO_PROFESSOR { get; set; }
        public Nullable<bool> STATUS_PROFESSOR { get; set; }
        public string CONTATO_EMERGENCIA_PROFESSOR { get; set; }
        public string GRAU_INSTRU_PROFESSOR { get; set; }
        public string ESTADO_CIVIL_PROFESSOR { get; set; }
        public Nullable<bool> VALE_ALIMENTACAO_PROF { get; set; }
        public Nullable<bool> VALE_TRANSPORTE_PROF { get; set; }
    
        public virtual ICollection<TB_MENCAO> TB_MENCAO { get; set; }
        public virtual ICollection<TB_SALA_DE_VIDEO> TB_SALA_DE_VIDEO { get; set; }
        public virtual ICollection<TB_TURMA> TB_TURMA { get; set; }
    }
}
