//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM_4_FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RESPONSAVEL
    {
        public TB_RESPONSAVEL()
        {
            this.TB_ALUNO = new HashSet<TB_ALUNO>();
        }
    
        public int COD_RESP { get; set; }
        public string NOME_RESP { get; set; }
        public decimal CPF_RESP { get; set; }
        public string RG_RESP { get; set; }
        public decimal TEL_RESP { get; set; }
        public string EMAIL_RESP { get; set; }
    
        public virtual ICollection<TB_ALUNO> TB_ALUNO { get; set; }
    }
}
