//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM_4_FUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TURMA
    {
        public TB_TURMA()
        {
            this.TB_ALUNO = new HashSet<TB_ALUNO>();
        }
    
        public int COD_TURMA { get; set; }
        public int COD_FUNC { get; set; }
        public string NOME_TURMA { get; set; }
        public string DISCIPLINA { get; set; }
        public Nullable<System.TimeSpan> HORA_TURMA { get; set; }
        public Nullable<int> DIA_TURMA { get; set; }
        public Nullable<System.DateTime> DATA_INI { get; set; }
        public Nullable<System.DateTime> DATA_FIN { get; set; }
    
        public virtual TB_FUNCIONARIO TB_FUNCIONARIO { get; set; }
        public virtual ICollection<TB_ALUNO> TB_ALUNO { get; set; }
    }
}
